name: chat
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^1.23.0
  cloud_firestore: ^3.4.9
  firebase_storage: ^10.3.9
  firebase_auth: ^3.10.0
  google_sign_in: ^5.4.2
  image_picker: ^0.8.5+3
  file_picker: ^4.1.3
  dio: ^4.0.6
  path_provider: ^2.0.11
  open_file: ^3.2.1
  # camera_camera: ^2.0.2
  camera: ^0.10.0+3

  rxdart: ^0.26.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

  assets: 
    - images/person.png
